---
training:
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL01_3_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL01_3_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL02_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL02_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL03_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL03_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL04_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL04_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL05_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL05_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL06_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL06_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL07_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL07_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL08_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL08_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL09_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL09_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL10_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL10_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL11_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL11_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL12_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL12_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL13_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL13_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL14_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL14_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL15_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL15_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL16_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL16_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL17_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL17_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL18_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL18_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL19_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL19_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL20_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL20_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL21_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL21_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL22_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL22_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL23_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL23_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL24_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL24_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL25_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL25_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL26_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL26_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL27_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL27_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL28_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL28_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL29_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL29_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL30_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL30_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL31_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL31_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL32_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL32_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL33_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL33_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL34_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL34_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL35_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL35_1_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL36_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL36_1_HE.xml
