---
training:
    - 
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0001_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0001_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0014_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0014_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0003_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0003_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0004_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0004_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0005_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0005_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0006_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0006_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0007_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0007_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0008_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0008_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0015_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0015_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0010_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0010_HE_fixed.xml

    
validation:
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0002_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0002_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0012_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0012_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0009_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0009_HE_fixed.xml
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0011_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0011_HE_fixed.xml 
    -
        wsi: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0013_HE.tiff
        wsa: 
            path: /data/archief/AMC-data/Barrett/Bolero/RB0013_HE_fixed.xml 

