---
# Bolero
test:
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0001_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0001_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0002_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0002_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0003_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0003_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0004_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0004_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0005_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0005_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0006_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0006_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0007_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0007_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0008_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0008_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0009_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0009_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0010_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0010_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0011_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0011_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0012_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0012_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0013_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0013_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0014_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0014_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0015_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0015_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0016_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0016_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0018_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0018_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0019_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0019_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0020_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0020_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0021_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0021_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0022_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0022_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0023_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0023_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0024_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0024_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0025_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0025_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0026_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0026_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0027_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0027_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0028_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0028_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0030_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0030_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0031_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0031_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0032_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0032_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0033_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0033_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0034_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0034_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0035_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0035_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0036_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0036_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0038_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0038_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0039_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0039_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0041_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0041_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0042_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0042_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0043_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0043_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0044_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0044_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0045_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0045_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0046_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0046_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0047_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0047_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0048_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0048_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0049_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0049_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0050_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0050_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0051_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0051_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0052_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0052_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0053_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0053_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0054_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0054_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0055_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/Bolero/RB0055_HE.xml
