---
training:
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL006_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL006_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL007_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL007_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_02_02_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_02_02_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_03_04_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_03_04_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL015_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL015_01_03_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL022_01_01_03_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL022_01_01_03_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL025_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL025_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL026_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL026_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL030_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL030_01_03_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL035_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL035_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL036_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL036_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL042_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL042_01_03_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL044_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL044_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL046_02_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL046_02_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL049_01_04_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL049_01_04_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL054_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL054_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL056_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL056_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL059_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL059_01_03_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL061_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL061_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL062_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL062_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL076_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL076_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL080_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL080_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL086_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL086_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL108_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL108_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL111_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL111_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL146_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL146_01_03_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL147_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL147_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL150_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL150_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL155_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL155_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL168_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL168_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL169_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL169_01_02_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL185_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL185_01_01_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL187_01_05_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL187_01_05_01_HE.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL195_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL195_01_02_01_HE.xml
