wholeslidedata:
    default:
        yaml_source: data.yml
        seed: 2

        label_map:
            e-stroma: 1
            ndbe-g: 2
            lgd-g: 3
            hgd-g: 4
           
        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 8
            spacing: 0.25
            shape: [512, 512, 3]
            
        label_sampler:
            attribute: OrderedLabelSampler

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: UniformPointSampler

