wholeslidedata:
    default:
        yaml_source: data.yml
        seed: 2

        label_map:
            ndbe-g: 1
            lgd-g: 2
            hgd-g: 3
#            e-stroma: 4
#            squamous-t: 5
           
        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 4
            spacing: 1
            shape: [512, 512, 3]
            
        label_sampler:
            attribute: OrderedLabelSampler

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: UniformPointSampler

