---
training:
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL12_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL12_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL08_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL08_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL29_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL29_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL35_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL35_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL17_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL17_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL26_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL26_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL22_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL22_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL27_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL27_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL25_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL25_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL28_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL28_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL13_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL13_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL16_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL16_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL10_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL10_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL02_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL02_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL19_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL19_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL20_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL20_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL32_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL32_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL36_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL36_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL09_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL09_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL31_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL31_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL21_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL21_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL33_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL33_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL06_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL06_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL23_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL23_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL04_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL04_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL05_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL05_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL03_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL03_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL07_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL07_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL24_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL24_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL30_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL30_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL15_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL15_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL01_3_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL01_3_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL14_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL14_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL147_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL147_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL030_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL030_01_03_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL046_02_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL046_02_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL146_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL146_01_03_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL108_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL108_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL195_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL195_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL025_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL025_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_02_02_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_02_02_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL080_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL080_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL059_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL059_01_03_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL015_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL015_01_03_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL062_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL062_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL168_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL168_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL086_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL086_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL076_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL076_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL026_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL026_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL054_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL054_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL187_01_05_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL187_01_05_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL150_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL150_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL036_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL036_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL185_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL185_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL111_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL111_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL155_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL155_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL035_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL035_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL056_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL056_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL022_01_01_03_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL022_01_01_03_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL007_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL007_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL049_01_04_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL049_01_04_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL042_01_03_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL042_01_03_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL006_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL006_01_01_01_HE_fixed.xml

validation:
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL11_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL11_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL34_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL34_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/ASL/ASL18_1_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/ASL/ASL18_1_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL044_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL044_01_02_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL061_01_01_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL061_01_01_01_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_03_04_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL013_02_03_04_HE_fixed.xml
    -
        wsi:
            path: /data/archief/AMC-data/Barrett/LANS/RL169_01_02_01_HE.tiff
        wsa:
            path: /data/archief/AMC-data/Barrett/LANS/RL169_01_02_01_HE_fixed.xml