wholeslidedata:
    default:
        yaml_source: data.yml
        seed: 2

        # todo: add squamous
        label_map:
            e-stroma: 1
            ndbe-g: 2
            lgd-g: 3
            hgd-g: 4
           
        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 8
            spacing: 1
            shape: [512, 512, 3]
            y_shape: [324, 324]
            
        label_sampler:
            attribute: OrderedLabelSampler

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: UniformPointSampler
            #buffer: -256                       # (to sample fully within the ROI)
            
        sample_callbacks:
            - module: wholeslidedata.samplers.callbacks
              attribute: FitOutput
              output_shape: [324, 324]
              

unet:

    # model
    n_channels: 3
    n_classes: 3
    # depth: 4
    # n_convs: 2
    # n_filters: 
    # batch_norm: True

    # training 
    learning_rate: 0.0005
    epochs: 100
    cpus: 4
    #gpus: 2
    
            

