wholeslidedata:
    default:
        yaml_source: split_ASL_LANS_RBE.yml
        seed: 2
        associations:
            exact_match: True

        label_map:
            ndbe-g: 1
            lgd-g: 2
            hgd-g: 3
#            e-stroma: 4
#            squamous-t: 5
           
        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 10
            spacing: 1
            shape: [1024, 1024, 3]
            y_shape: [836, 836]
            
        point_sampler:
            attribute: RandomPointSampler
            
        sample_callbacks:
            - module: wholeslidedata.samplers.callbacks
              attribute: FitOutput
              output_shape: [836, 836]
              
unet:
    # model
    n_channels: 3
    n_classes: 3

    # training
    learning_rate: 0.005
    epochs: 1000
    train_batches: 100        # 100*10 = 1000 train patches
    val_batches: 20           # 20*10  = 200 validation patches
    gpus: 2
    cpus: 1
    
            

