wholeslidedata:
    default:
        yaml_source: train_split.yml
        seed: 2

        label_map:
            ndbe-g: 1
            lgd-g: 2
            hgd-g: 3
#            e-stroma: 4
#            squamous-t: 5
           
        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 25
            spacing: 1
            shape: [512, 512, 3]
            y_shape: [324, 324]
            
        point_sampler:
            attribute: RandomPointSampler
            buffer: -256
            
        sample_callbacks:
            - module: wholeslidedata.samplers.callbacks
              attribute: FitOutput
              output_shape: [324, 324]
              
unet:
    # model
    n_channels: 3
    n_classes: 3

    # training
    learning_rate: 0.005
    epochs: 100
    train_batches: 1000
    val_batches: 100
    gpus: 1
    cpus: 1
    
            

